import React, { useMemo, useState } from "react";
import { ActivityIndicator, FlatList, RefreshControl, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { AlertTriangle, BriefcaseBusiness, ShieldCheck, UsersRound } from "lucide-react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import type { OfficerAvailability } from "../../types";
import { useOfficerAvailability } from "../../hooks/useAlerts";
import { Badge } from "../../components/ui/Badge";
import { Card } from "../../components/ui/Card";
import { useLanguage } from "../../context/LanguageContext";
import { useTheme } from "../../context/ThemeContext";

type AvailabilityFilter = "ALL" | "ON_SHIFT" | "HIGH";

export const AdminOfficerAvailabilityScreen: React.FC = () => {
  const insets = useSafeAreaInsets();
  const { colors, isDark } = useTheme();
  const { language } = useLanguage();
  const [filter, setFilter] = useState<AvailabilityFilter>("ALL");
  const availability = useOfficerAvailability();
  const rows = useMemo(() => (availability.data ?? []).filter((item) => filter === "ALL" || (filter === "ON_SHIFT" ? item.shiftStatus === "ON_SHIFT" : item.workloadLevel === "HIGH")), [availability.data, filter]);
  const copy = language === "vi"
    ? { title: "Cán bộ", subtitle: "Khả dụng và khối lượng công việc trực tiếp", all: "Tất cả", shift: "Đang trong ca", high: "Quá tải", tasks: "Nhiệm vụ đang xử lý", assigned: "Đã phân công", processing: "Đang thực hiện", off: "Ngoài ca", on: "Trong ca", empty: "Không có cán bộ phù hợp", error: "Không thể tải tình trạng cán bộ", normal: "Bình thường", moderate: "Trung bình", workload: "Khối lượng" }
    : { title: "Officers", subtitle: "Live availability and workload", all: "All", shift: "On shift", high: "High workload", tasks: "Active tasks", assigned: "Assigned", processing: "In progress", off: "Off shift", on: "On shift", empty: "No officers match this filter", error: "Officer availability could not be loaded", normal: "Normal", moderate: "Moderate", workload: "Workload" };
  const workloadLabel = (item: OfficerAvailability) => item.workloadLevel === "HIGH" ? copy.high : item.workloadLevel === "MODERATE" ? copy.moderate : copy.normal;
  const workloadColor = (level: OfficerAvailability["workloadLevel"]) => level === "HIGH" ? { bg: "#FEE2E2", text: "#B91C1C" } : level === "MODERATE" ? { bg: "#FEF3C7", text: "#B45309" } : { bg: "#DCFCE7", text: "#15803D" };
  const renderItem = ({ item }: { item: OfficerAvailability }) => {
    const workload = workloadColor(item.workloadLevel);
    return <Card style={styles.card}><View style={styles.cardHeader}><View style={[styles.avatar, { backgroundColor: isDark ? "rgba(59,130,246,0.24)" : "#DBEAFE" }]}><ShieldCheck size={21} color={colors.secondary} /></View><View style={styles.nameBlock}><Text style={[styles.name, { color: colors.text }]}>{item.officer.fullName}</Text><Text style={[styles.email, { color: colors.textMuted }]} numberOfLines={1}>{item.officer.email}</Text></View><Badge label={item.shiftStatus === "ON_SHIFT" ? copy.on : copy.off} type="custom" bgColor={item.shiftStatus === "ON_SHIFT" ? "#CCFBF1" : (isDark ? "#334155" : "#E2E8F0")} textColor={item.shiftStatus === "ON_SHIFT" ? "#0F766E" : colors.textMuted} /></View><View style={styles.metricRow}><View style={styles.metric}><Text style={[styles.metricValue, { color: colors.text }]}>{item.activeTaskCount}</Text><Text style={[styles.metricLabel, { color: colors.textMuted }]}>{copy.tasks}</Text></View><View style={styles.metric}><Text style={[styles.metricValue, { color: colors.text }]}>{item.assignedCount}</Text><Text style={[styles.metricLabel, { color: colors.textMuted }]}>{copy.assigned}</Text></View><View style={styles.metric}><Text style={[styles.metricValue, { color: colors.text }]}>{item.inProgressCount}</Text><Text style={[styles.metricLabel, { color: colors.textMuted }]}>{copy.processing}</Text></View></View><View style={[styles.workload, { backgroundColor: workload.bg }]}><BriefcaseBusiness size={14} color={workload.text} /><Text style={[styles.workloadText, { color: workload.text }]}>{copy.workload}: {workloadLabel(item)}</Text></View></Card>;
  };
  return <View style={[styles.container, { backgroundColor: colors.background, paddingTop: insets.top }]}><View style={[styles.header, { backgroundColor: colors.surface, borderBottomColor: colors.border }]}><View style={styles.headerCopy}><Text style={[styles.title, { color: colors.text }]}>{copy.title}</Text><Text style={[styles.subtitle, { color: colors.textMuted }]}>{copy.subtitle}</Text></View><View style={[styles.headerIcon, { backgroundColor: isDark ? "rgba(124,58,237,0.3)" : "#F3E8FF" }]}><UsersRound size={21} color="#7C3AED" /></View></View><View style={styles.filters}>{([{ id: "ALL", label: copy.all }, { id: "ON_SHIFT", label: copy.shift }, { id: "HIGH", label: copy.high }] as const).map((option) => <TouchableOpacity key={option.id} onPress={() => setFilter(option.id)} accessibilityRole="button" accessibilityState={{ selected: filter === option.id }} style={[styles.chip, { borderColor: filter === option.id ? "#7C3AED" : colors.border, backgroundColor: filter === option.id ? (isDark ? "rgba(124,58,237,0.3)" : "#F3E8FF") : colors.surface }]}><Text style={{ color: filter === option.id ? "#7C3AED" : colors.textMuted, fontSize: 12, fontWeight: "800" }}>{option.label}</Text></TouchableOpacity>)}</View><FlatList data={rows} keyExtractor={(item) => item.officer._id} renderItem={renderItem} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={availability.isRefetching} onRefresh={() => availability.refetch()} tintColor="#7C3AED" />} ListEmptyComponent={<View style={styles.state}>{availability.isLoading ? <ActivityIndicator color="#7C3AED" /> : <AlertTriangle size={38} color={colors.textMuted} />}<Text style={[styles.stateText, { color: colors.text }]}>{availability.isError ? copy.error : copy.empty}</Text>{availability.isError ? <TouchableOpacity onPress={() => availability.refetch()}><Text style={{ color: "#7C3AED", fontWeight: "800" }}>{language === "vi" ? "Thử lại" : "Retry"}</Text></TouchableOpacity> : null}</View>} /></View>;
};

const styles = StyleSheet.create({ container: { flex: 1 }, header: { minHeight: 76, flexDirection: "row", alignItems: "center", paddingHorizontal: 20, borderBottomWidth: StyleSheet.hairlineWidth }, headerCopy: { flex: 1 }, title: { fontSize: 22, fontWeight: "800" }, subtitle: { fontSize: 12, marginTop: 3 }, headerIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, filters: { flexDirection: "row", gap: 8, paddingHorizontal: 16, paddingVertical: 12 }, chip: { minHeight: 36, paddingHorizontal: 12, justifyContent: "center", borderRadius: 18, borderWidth: 1 }, content: { paddingHorizontal: 16, paddingBottom: 36, flexGrow: 1 }, card: { padding: 15, borderRadius: 18, marginBottom: 11 }, cardHeader: { flexDirection: "row", alignItems: "center", gap: 10 }, avatar: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 14 }, nameBlock: { flex: 1, minWidth: 0 }, name: { fontSize: 15, fontWeight: "800" }, email: { fontSize: 11, marginTop: 2 }, metricRow: { flexDirection: "row", marginTop: 16, gap: 8 }, metric: { flex: 1 }, metricValue: { fontSize: 18, fontWeight: "900" }, metricLabel: { fontSize: 10, marginTop: 2, lineHeight: 13 }, workload: { alignSelf: "flex-start", marginTop: 13, minHeight: 30, borderRadius: 10, paddingHorizontal: 9, flexDirection: "row", alignItems: "center", gap: 5 }, workloadText: { fontSize: 11, fontWeight: "800" }, state: { flex: 1, minHeight: 330, alignItems: "center", justifyContent: "center", gap: 12, paddingHorizontal: 28 }, stateText: { fontSize: 14, fontWeight: "700", textAlign: "center" } });
